#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CosmeticFirecracker

#include "Basic.hpp"

#include "BP_CosmeticFirecracker_classes.hpp"
#include "BP_CosmeticFirecracker_parameters.hpp"


namespace SDK
{

// Function BP_CosmeticFirecracker.BP_CosmeticFirecracker_C.BndEvt__BP_CosmeticFirecracker_ProjectileMovement_K2Node_ComponentBoundEvent_0_OnProjectileStopDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FHitResult                       ImpactResult                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_CosmeticFirecracker_C::BndEvt__BP_CosmeticFirecracker_ProjectileMovement_K2Node_ComponentBoundEvent_0_OnProjectileStopDelegate__DelegateSignature(const struct FHitResult& ImpactResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticFirecracker_C", "BndEvt__BP_CosmeticFirecracker_ProjectileMovement_K2Node_ComponentBoundEvent_0_OnProjectileStopDelegate__DelegateSignature");

	Params::BP_CosmeticFirecracker_C_BndEvt__BP_CosmeticFirecracker_ProjectileMovement_K2Node_ComponentBoundEvent_0_OnProjectileStopDelegate__DelegateSignature Parms{};

	Parms.ImpactResult = std::move(ImpactResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CosmeticFirecracker.BP_CosmeticFirecracker_C.ExecuteUbergraph_BP_CosmeticFirecracker
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CosmeticFirecracker_C::ExecuteUbergraph_BP_CosmeticFirecracker(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticFirecracker_C", "ExecuteUbergraph_BP_CosmeticFirecracker");

	Params::BP_CosmeticFirecracker_C_ExecuteUbergraph_BP_CosmeticFirecracker Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CosmeticFirecracker.BP_CosmeticFirecracker_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CosmeticFirecracker_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticFirecracker_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CosmeticFirecracker.BP_CosmeticFirecracker_C.SetCollisionEnabled
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    Ignore                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CosmeticFirecracker_C::SetCollisionEnabled(class AActor* Target, bool Ignore)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticFirecracker_C", "SetCollisionEnabled");

	Params::BP_CosmeticFirecracker_C_SetCollisionEnabled Parms{};

	Parms.Target = Target;
	Parms.Ignore = Ignore;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CosmeticFirecracker.BP_CosmeticFirecracker_C.SetSpeed
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_CosmeticFirecracker_C::SetSpeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CosmeticFirecracker_C", "SetSpeed");

	UObject::ProcessEvent(Func, nullptr);
}

}

