#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FloodLight

#include "Basic.hpp"

#include "BP_FloodLight_classes.hpp"
#include "BP_FloodLight_parameters.hpp"


namespace SDK
{

// Function BP_FloodLight.BP_FloodLight_C.ExecuteUbergraph_BP_FloodLight
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FloodLight_C::ExecuteUbergraph_BP_FloodLight(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FloodLight_C", "ExecuteUbergraph_BP_FloodLight");

	Params::BP_FloodLight_C_ExecuteUbergraph_BP_FloodLight Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FloodLight.BP_FloodLight_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_FloodLight_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FloodLight_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FloodLight.BP_FloodLight_C.Turn On
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enable                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FloodLight_C::Turn_On(bool Enable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FloodLight_C", "Turn On");

	Params::BP_FloodLight_C_Turn_On Parms{};

	Parms.Enable = Enable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FloodLight.BP_FloodLight_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_FloodLight_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FloodLight_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

