#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Hedge_BranchSpawner

#include "Basic.hpp"

#include "JP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Hedge_BranchSpawner.BP_Hedge_BranchSpawner_C
// 0x0000 (0x02D0 - 0x02D0)
class ABP_Hedge_BranchSpawner_C final : public ATaskSpawner
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Hedge_BranchSpawner_C">();
	}
	static class ABP_Hedge_BranchSpawner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Hedge_BranchSpawner_C>();
	}
};
static_assert(alignof(ABP_Hedge_BranchSpawner_C) == 0x000008, "Wrong alignment on ABP_Hedge_BranchSpawner_C");
static_assert(sizeof(ABP_Hedge_BranchSpawner_C) == 0x0002D0, "Wrong size on ABP_Hedge_BranchSpawner_C");

}

