#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Seagull130CU_Crate

#include "Basic.hpp"

#include "BP_HouseAdditionCrate_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Seagull130CU_Crate.BP_Seagull130CU_Crate_C
// 0x0000 (0x06F0 - 0x06F0)
class ABP_Seagull130CU_Crate_C final : public ABP_HouseAdditionCrate_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Seagull130CU_Crate_C">();
	}
	static class ABP_Seagull130CU_Crate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Seagull130CU_Crate_C>();
	}
};
static_assert(alignof(ABP_Seagull130CU_Crate_C) == 0x000010, "Wrong alignment on ABP_Seagull130CU_Crate_C");
static_assert(sizeof(ABP_Seagull130CU_Crate_C) == 0x0006F0, "Wrong size on ABP_Seagull130CU_Crate_C");

}

