#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SOD_TrimHedges

#include "Basic.hpp"

#include "JP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SOD_TrimHedges.SOD_TrimHedges_C
// 0x0008 (0x0058 - 0x0050)
class USOD_TrimHedges_C final : public USubObjectiveDefinition
{
public:
	int32                                         HedgeCount;                                        // 0x0050(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SOD_TrimHedges_C">();
	}
	static class USOD_TrimHedges_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USOD_TrimHedges_C>();
	}
};
static_assert(alignof(USOD_TrimHedges_C) == 0x000008, "Wrong alignment on USOD_TrimHedges_C");
static_assert(sizeof(USOD_TrimHedges_C) == 0x000058, "Wrong size on USOD_TrimHedges_C");
static_assert(offsetof(USOD_TrimHedges_C, HedgeCount) == 0x000050, "Member 'USOD_TrimHedges_C::HedgeCount' has a wrong offset!");

}

