#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WI_CheatInputField

#include "Basic.hpp"


namespace SDK::Params
{

// Function WI_CheatInputField.WI_CheatInputField_C.ExecuteUbergraph_WI_CheatInputField
// 0x0028 (0x0028 - 0x0000)
struct WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetFullCommand_ReturnValue;               // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0018(0x0010)()
};
static_assert(alignof(WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField) == 0x000008, "Wrong alignment on WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField");
static_assert(sizeof(WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField) == 0x000028, "Wrong size on WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField");
static_assert(offsetof(WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField, EntryPoint) == 0x000000, "Member 'WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField::EntryPoint' has a wrong offset!");
static_assert(offsetof(WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField, K2Node_Event_IsDesignTime) == 0x000004, "Member 'WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField, CallFunc_GetFullCommand_ReturnValue) == 0x000008, "Member 'WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField::CallFunc_GetFullCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField, CallFunc_Conv_StringToText_ReturnValue) == 0x000018, "Member 'WI_CheatInputField_C_ExecuteUbergraph_WI_CheatInputField::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

// Function WI_CheatInputField.WI_CheatInputField_C.OnClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WI_CheatInputField_C_OnClicked__DelegateSignature final
{
public:
	class UWI_CheatInputField_C*                  CheatInputField;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_CheatInputField_C_OnClicked__DelegateSignature) == 0x000008, "Wrong alignment on WI_CheatInputField_C_OnClicked__DelegateSignature");
static_assert(sizeof(WI_CheatInputField_C_OnClicked__DelegateSignature) == 0x000008, "Wrong size on WI_CheatInputField_C_OnClicked__DelegateSignature");
static_assert(offsetof(WI_CheatInputField_C_OnClicked__DelegateSignature, CheatInputField) == 0x000000, "Member 'WI_CheatInputField_C_OnClicked__DelegateSignature::CheatInputField' has a wrong offset!");

// Function WI_CheatInputField.WI_CheatInputField_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WI_CheatInputField_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_CheatInputField_C_PreConstruct) == 0x000001, "Wrong alignment on WI_CheatInputField_C_PreConstruct");
static_assert(sizeof(WI_CheatInputField_C_PreConstruct) == 0x000001, "Wrong size on WI_CheatInputField_C_PreConstruct");
static_assert(offsetof(WI_CheatInputField_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WI_CheatInputField_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WI_CheatInputField.WI_CheatInputField_C.GetFullCommand
// 0x0050 (0x0050 - 0x0000)
struct WI_CheatInputField_C_GetFullCommand final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0010(0x0010)()
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_CheatInputField_C_GetFullCommand) == 0x000008, "Wrong alignment on WI_CheatInputField_C_GetFullCommand");
static_assert(sizeof(WI_CheatInputField_C_GetFullCommand) == 0x000050, "Wrong size on WI_CheatInputField_C_GetFullCommand");
static_assert(offsetof(WI_CheatInputField_C_GetFullCommand, ReturnValue) == 0x000000, "Member 'WI_CheatInputField_C_GetFullCommand::ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_CheatInputField_C_GetFullCommand, CallFunc_GetText_ReturnValue) == 0x000010, "Member 'WI_CheatInputField_C_GetFullCommand::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_CheatInputField_C_GetFullCommand, CallFunc_Concat_StrStr_ReturnValue) == 0x000020, "Member 'WI_CheatInputField_C_GetFullCommand::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_CheatInputField_C_GetFullCommand, CallFunc_Conv_TextToString_ReturnValue) == 0x000030, "Member 'WI_CheatInputField_C_GetFullCommand::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_CheatInputField_C_GetFullCommand, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000040, "Member 'WI_CheatInputField_C_GetFullCommand::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");

}

