#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WI_SocialFriendInteraction

#include "Basic.hpp"


namespace SDK::Params
{

// Function WI_SocialFriendInteraction.WI_SocialFriendInteraction_C.ExecuteUbergraph_WI_SocialFriendInteraction
// 0x0004 (0x0004 - 0x0000)
struct WI_SocialFriendInteraction_C_ExecuteUbergraph_WI_SocialFriendInteraction final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_SocialFriendInteraction_C_ExecuteUbergraph_WI_SocialFriendInteraction) == 0x000004, "Wrong alignment on WI_SocialFriendInteraction_C_ExecuteUbergraph_WI_SocialFriendInteraction");
static_assert(sizeof(WI_SocialFriendInteraction_C_ExecuteUbergraph_WI_SocialFriendInteraction) == 0x000004, "Wrong size on WI_SocialFriendInteraction_C_ExecuteUbergraph_WI_SocialFriendInteraction");
static_assert(offsetof(WI_SocialFriendInteraction_C_ExecuteUbergraph_WI_SocialFriendInteraction, EntryPoint) == 0x000000, "Member 'WI_SocialFriendInteraction_C_ExecuteUbergraph_WI_SocialFriendInteraction::EntryPoint' has a wrong offset!");

}

