#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WI_WelcomePassPreview_Winscreen_V2

#include "Basic.hpp"

#include "WI_WelcomePassPreview_Winscreen_V2_classes.hpp"
#include "WI_WelcomePassPreview_Winscreen_V2_parameters.hpp"


namespace SDK
{

// Function WI_WelcomePassPreview_Winscreen_V2.WI_WelcomePassPreview_Winscreen_V2_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWI_WelcomePassPreview_Winscreen_V2_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WI_WelcomePassPreview_Winscreen_V2_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WI_WelcomePassPreview_Winscreen_V2.WI_WelcomePassPreview_Winscreen_V2_C.EditorOnlyPopulateScrollBox
// (BlueprintCallable, BlueprintEvent)

void UWI_WelcomePassPreview_Winscreen_V2_C::EditorOnlyPopulateScrollBox()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WI_WelcomePassPreview_Winscreen_V2_C", "EditorOnlyPopulateScrollBox");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WI_WelcomePassPreview_Winscreen_V2.WI_WelcomePassPreview_Winscreen_V2_C.ExecuteUbergraph_WI_WelcomePassPreview_Winscreen_V2
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWI_WelcomePassPreview_Winscreen_V2_C::ExecuteUbergraph_WI_WelcomePassPreview_Winscreen_V2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WI_WelcomePassPreview_Winscreen_V2_C", "ExecuteUbergraph_WI_WelcomePassPreview_Winscreen_V2");

	Params::WI_WelcomePassPreview_Winscreen_V2_C_ExecuteUbergraph_WI_WelcomePassPreview_Winscreen_V2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WI_WelcomePassPreview_Winscreen_V2.WI_WelcomePassPreview_Winscreen_V2_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWI_WelcomePassPreview_Winscreen_V2_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WI_WelcomePassPreview_Winscreen_V2_C", "PreConstruct");

	Params::WI_WelcomePassPreview_Winscreen_V2_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

