#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WI_WinscreenSubBase

#include "Basic.hpp"

#include "WI_WinscreenSubBase_classes.hpp"
#include "WI_WinscreenSubBase_parameters.hpp"


namespace SDK
{

// Function WI_WinscreenSubBase.WI_WinscreenSubBase_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWI_WinscreenSubBase_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WI_WinscreenSubBase_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WI_WinscreenSubBase.WI_WinscreenSubBase_C.ExecuteUbergraph_WI_WinscreenSubBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWI_WinscreenSubBase_C::ExecuteUbergraph_WI_WinscreenSubBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WI_WinscreenSubBase_C", "ExecuteUbergraph_WI_WinscreenSubBase");

	Params::WI_WinscreenSubBase_C_ExecuteUbergraph_WI_WinscreenSubBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WI_WinscreenSubBase.WI_WinscreenSubBase_C.IsOnWinningTeam
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWI_WinscreenSubBase_C::IsOnWinningTeam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WI_WinscreenSubBase_C", "IsOnWinningTeam");

	Params::WI_WinscreenSubBase_C_IsOnWinningTeam Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WI_WinscreenSubBase.WI_WinscreenSubBase_C.StateChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_WinscreenState                        NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWI_WinscreenSubBase_C::StateChanged__DelegateSignature(E_WinscreenState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WI_WinscreenSubBase_C", "StateChanged__DelegateSignature");

	Params::WI_WinscreenSubBase_C_StateChanged__DelegateSignature Parms{};

	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}

}

