#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EI_GooseLeash

#include "Basic.hpp"

#include "BP_EquipmentInstance_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EI_GooseLeash.EI_GooseLeash_C
// 0x0008 (0x0148 - 0x0140)
class UEI_GooseLeash_C final : public UBP_EquipmentInstance_C
{
public:
	class ABP_Goose_C*                            AssociatedGoose;                                   // 0x0140(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EI_GooseLeash_C">();
	}
	static class UEI_GooseLeash_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEI_GooseLeash_C>();
	}
};
static_assert(alignof(UEI_GooseLeash_C) == 0x000008, "Wrong alignment on UEI_GooseLeash_C");
static_assert(sizeof(UEI_GooseLeash_C) == 0x000148, "Wrong size on UEI_GooseLeash_C");
static_assert(offsetof(UEI_GooseLeash_C, AssociatedGoose) == 0x000140, "Member 'UEI_GooseLeash_C::AssociatedGoose' has a wrong offset!");

}

