#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ELeloiIdleStates

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ELeloiIdleStates.ELeloiIdleStates
// NumValues: 0x0004
enum class ELeloiIdleStates : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	ELeloiIdleStates_MAX                     = 3,
};

}

