#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_HomingWrenchTargeting

#include "Basic.hpp"

#include "GCN_HomingWrenchTargeting_classes.hpp"
#include "GCN_HomingWrenchTargeting_parameters.hpp"


namespace SDK
{

// Function GCN_HomingWrenchTargeting.GCN_HomingWrenchTargeting_C.ExecuteUbergraph_GCN_HomingWrenchTargeting
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGCN_HomingWrenchTargeting_C::ExecuteUbergraph_GCN_HomingWrenchTargeting(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HomingWrenchTargeting_C", "ExecuteUbergraph_GCN_HomingWrenchTargeting");

	Params::GCN_HomingWrenchTargeting_C_ExecuteUbergraph_GCN_HomingWrenchTargeting Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GCN_HomingWrenchTargeting.GCN_HomingWrenchTargeting_C.FilterTargets
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FHitResult>               Array                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// TArray<class AActor*>                   Return                                                 (Parm, OutParm)

void AGCN_HomingWrenchTargeting_C::FilterTargets(TArray<struct FHitResult>& Array, TArray<class AActor*>* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HomingWrenchTargeting_C", "FilterTargets");

	Params::GCN_HomingWrenchTargeting_C_FilterTargets Parms{};

	Parms.Array = std::move(Array);

	UObject::ProcessEvent(Func, &Parms);

	Array = std::move(Parms.Array);

	if (Return != nullptr)
		*Return = std::move(Parms.Return);
}


// Function GCN_HomingWrenchTargeting.GCN_HomingWrenchTargeting_C.Local_Add
// (BlueprintCallable, BlueprintEvent)

void AGCN_HomingWrenchTargeting_C::Local_Add()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HomingWrenchTargeting_C", "Local_Add");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_HomingWrenchTargeting.GCN_HomingWrenchTargeting_C.Local_Remove
// (BlueprintCallable, BlueprintEvent)

void AGCN_HomingWrenchTargeting_C::Local_Remove()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HomingWrenchTargeting_C", "Local_Remove");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_HomingWrenchTargeting.GCN_HomingWrenchTargeting_C.On Tracking Timer Elapsed
// (BlueprintCallable, BlueprintEvent)

void AGCN_HomingWrenchTargeting_C::On_Tracking_Timer_Elapsed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HomingWrenchTargeting_C", "On Tracking Timer Elapsed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCN_HomingWrenchTargeting.GCN_HomingWrenchTargeting_C.SetTrackingComponentVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bNewVisibility                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGCN_HomingWrenchTargeting_C::SetTrackingComponentVisibility(bool bNewVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCN_HomingWrenchTargeting_C", "SetTrackingComponentVisibility");

	Params::GCN_HomingWrenchTargeting_C_SetTrackingComponentVisibility Parms{};

	Parms.bNewVisibility = bNewVisibility;

	UObject::ProcessEvent(Func, &Parms);
}

}

