#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_ProjectileDamageDealt_Tomato

#include "Basic.hpp"

#include "GCN_ProjectileDamageDealt_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_ProjectileDamageDealt_Tomato.GCN_ProjectileDamageDealt_Tomato_C
// 0x0000 (0x0360 - 0x0360)
class UGCN_ProjectileDamageDealt_Tomato_C final : public UGCN_ProjectileDamageDealt_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_ProjectileDamageDealt_Tomato_C">();
	}
	static class UGCN_ProjectileDamageDealt_Tomato_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_ProjectileDamageDealt_Tomato_C>();
	}
};
static_assert(alignof(UGCN_ProjectileDamageDealt_Tomato_C) == 0x000008, "Wrong alignment on UGCN_ProjectileDamageDealt_Tomato_C");
static_assert(sizeof(UGCN_ProjectileDamageDealt_Tomato_C) == 0x000360, "Wrong size on UGCN_ProjectileDamageDealt_Tomato_C");

}

