#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_GenericSecondaryAnimationState

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_GenericSecondaryAnimationState.GE_GenericSecondaryAnimationState_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_GenericSecondaryAnimationState_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_GenericSecondaryAnimationState_C">();
	}
	static class UGE_GenericSecondaryAnimationState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_GenericSecondaryAnimationState_C>();
	}
};
static_assert(alignof(UGE_GenericSecondaryAnimationState_C) == 0x000008, "Wrong alignment on UGE_GenericSecondaryAnimationState_C");
static_assert(sizeof(UGE_GenericSecondaryAnimationState_C) == 0x000A70, "Wrong size on UGE_GenericSecondaryAnimationState_C");

}

