#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PA_GrantGameplayAbility

#include "Basic.hpp"

#include "PA_GrantGameplayAbility_classes.hpp"
#include "PA_GrantGameplayAbility_parameters.hpp"


namespace SDK
{

// Function PA_GrantGameplayAbility.PA_GrantGameplayAbility_C.ExecuteUbergraph_PA_GrantGameplayAbility
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPA_GrantGameplayAbility_C::ExecuteUbergraph_PA_GrantGameplayAbility(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PA_GrantGameplayAbility_C", "ExecuteUbergraph_PA_GrantGameplayAbility");

	Params::PA_GrantGameplayAbility_C_ExecuteUbergraph_PA_GrantGameplayAbility Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PA_GrantGameplayAbility.PA_GrantGameplayAbility_C.GrantGameplayAbility
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAbilitySystemComponentIW*        Target_ASC                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UPA_GrantGameplayAbility_C::GrantGameplayAbility(class UAbilitySystemComponentIW* Target_ASC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PA_GrantGameplayAbility_C", "GrantGameplayAbility");

	Params::PA_GrantGameplayAbility_C_GrantGameplayAbility Parms{};

	Parms.Target_ASC = Target_ASC;

	UObject::ProcessEvent(Func, &Parms);
}

}

