#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_AimAssistReticle

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function W_AimAssistReticle.W_AimAssistReticle_C.ExecuteUbergraph_W_AimAssistReticle
// 0x00E8 (0x00E8 - 0x0000)
struct W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0004(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GetCurrentSphereDistance_SphereDistance;  // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_CalculateConeProjectionAtDistance_ReturnValue; // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_CalculateSphericalProjectionRadiusAtDistance_ReturnValue; // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_CalculateSphericalProjectionRadiusAtDistance_ReturnValue_1; // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetAdjustedThickness_NewThickness;        // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_MakeStruct_LinearColor;                     // 0x0088(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast; // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast; // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast_1; // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast_1; // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast_2; // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast_2; // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Greater_DoubleDouble_B_ImplicitCast;      // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_CalculateSphericalProjectionRadiusAtDistance_Distance_ImplicitCast; // 0x00B8(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        K2Node_VariableSet_ReticeWidth_ImplicitCast;       // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_VariableSet_OriginalReticleWidth_ImplicitCast; // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1;   // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_Value_ImplicitCast; // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle) == 0x000008, "Wrong alignment on W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle");
static_assert(sizeof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle) == 0x0000E8, "Wrong size on W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, EntryPoint) == 0x000000, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, K2Node_Event_MyGeometry) == 0x000004, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, K2Node_Event_InDeltaTime) == 0x00003C, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_IsValid_ReturnValue) == 0x000040, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, K2Node_SwitchEnum_CmpSuccess) == 0x000041, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_GetCurrentSphereDistance_SphereDistance) == 0x000048, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_GetCurrentSphereDistance_SphereDistance' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_CalculateConeProjectionAtDistance_ReturnValue) == 0x000050, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_CalculateConeProjectionAtDistance_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x000054, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_CalculateSphericalProjectionRadiusAtDistance_ReturnValue) == 0x000058, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_CalculateSphericalProjectionRadiusAtDistance_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000060, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x000068, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_CalculateSphericalProjectionRadiusAtDistance_ReturnValue_1) == 0x000070, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_CalculateSphericalProjectionRadiusAtDistance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x000078, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_GetAdjustedThickness_NewThickness) == 0x000080, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_GetAdjustedThickness_NewThickness' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, K2Node_MakeStruct_LinearColor) == 0x000088, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::K2Node_MakeStruct_LinearColor' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast) == 0x000098, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast) == 0x00009C, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast_1) == 0x0000A0, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast_1) == 0x0000A4, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast_2) == 0x0000A8, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast_2) == 0x0000AC, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_Greater_DoubleDouble_B_ImplicitCast) == 0x0000B0, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_Greater_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_CalculateSphericalProjectionRadiusAtDistance_Distance_ImplicitCast) == 0x0000B8, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_CalculateSphericalProjectionRadiusAtDistance_Distance_ImplicitCast' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, K2Node_VariableSet_ReticeWidth_ImplicitCast) == 0x0000C0, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::K2Node_VariableSet_ReticeWidth_ImplicitCast' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x0000C8, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, K2Node_VariableSet_OriginalReticleWidth_ImplicitCast) == 0x0000D0, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::K2Node_VariableSet_OriginalReticleWidth_ImplicitCast' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1) == 0x0000D8, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle, CallFunc_SetScalarParameterValue_Value_ImplicitCast) == 0x0000E0, "Member 'W_AimAssistReticle_C_ExecuteUbergraph_W_AimAssistReticle::CallFunc_SetScalarParameterValue_Value_ImplicitCast' has a wrong offset!");

// Function W_AimAssistReticle.W_AimAssistReticle_C.Get_Reticle_Brush
// 0x00D0 (0x00D0 - 0x0000)
struct W_AimAssistReticle_C_Get_Reticle_Brush final
{
public:
	struct FSlateBrush                            ReturnValue;                                       // 0x0000(0x00D0)(Parm, OutParm, ReturnParm)
};
static_assert(alignof(W_AimAssistReticle_C_Get_Reticle_Brush) == 0x000010, "Wrong alignment on W_AimAssistReticle_C_Get_Reticle_Brush");
static_assert(sizeof(W_AimAssistReticle_C_Get_Reticle_Brush) == 0x0000D0, "Wrong size on W_AimAssistReticle_C_Get_Reticle_Brush");
static_assert(offsetof(W_AimAssistReticle_C_Get_Reticle_Brush, ReturnValue) == 0x000000, "Member 'W_AimAssistReticle_C_Get_Reticle_Brush::ReturnValue' has a wrong offset!");

// Function W_AimAssistReticle.W_AimAssistReticle_C.Get_Reticle_Visibility
// 0x0004 (0x0004 - 0x0000)
struct W_AimAssistReticle_C_Get_Reticle_Visibility final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              ResultVisibility;                                  // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ShouldEnableAssist_ReturnValue;           // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_AimAssistReticle_C_Get_Reticle_Visibility) == 0x000001, "Wrong alignment on W_AimAssistReticle_C_Get_Reticle_Visibility");
static_assert(sizeof(W_AimAssistReticle_C_Get_Reticle_Visibility) == 0x000004, "Wrong size on W_AimAssistReticle_C_Get_Reticle_Visibility");
static_assert(offsetof(W_AimAssistReticle_C_Get_Reticle_Visibility, ReturnValue) == 0x000000, "Member 'W_AimAssistReticle_C_Get_Reticle_Visibility::ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_Get_Reticle_Visibility, ResultVisibility) == 0x000001, "Member 'W_AimAssistReticle_C_Get_Reticle_Visibility::ResultVisibility' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_Get_Reticle_Visibility, CallFunc_ShouldEnableAssist_ReturnValue) == 0x000002, "Member 'W_AimAssistReticle_C_Get_Reticle_Visibility::CallFunc_ShouldEnableAssist_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_Get_Reticle_Visibility, CallFunc_BooleanAND_ReturnValue) == 0x000003, "Member 'W_AimAssistReticle_C_Get_Reticle_Visibility::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");

// Function W_AimAssistReticle.W_AimAssistReticle_C.GetCurrentSphereDistance
// 0x0590 (0x0590 - 0x0000)
struct W_AimAssistReticle_C_GetCurrentSphereDistance final
{
public:
	double                                        SphereDistance;                                    // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Start;                                             // 0x0008(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                End;                                               // 0x0020(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CameraForward;                                     // 0x0038(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CameraLocation;                                    // 0x0050(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Result;                                            // 0x0068(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x0078(0x0010)(ConstParm, ReferenceParm)
	struct FHitResult                             CallFunc_SphereTraceSingleByProfile_OutHit;        // 0x0088(0x00F8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_SphereTraceSingleByProfile_ReturnValue;   // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0181(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0182(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0183(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0184(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18C[0x4];                                      // 0x018C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0190(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x01A8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x01C0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x01D8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x01F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x01F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0200(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_BoneName;                  // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0218(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x021C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_224[0x4];                                      // 0x0224(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0228(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0240(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0258(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwner_ReturnValue_1;                   // 0x0270(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_VSize_ReturnValue;                        // 0x0278(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array_1;                          // 0x0280(0x0010)(ConstParm, ReferenceParm)
	struct FHitResult                             CallFunc_SphereTraceSingle_OutHit;                 // 0x0290(0x00F8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_SphereTraceSingle_ReturnValue;            // 0x0388(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_389[0x7];                                      // 0x0389(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue;          // 0x0390(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit_1;            // 0x03A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap_1;         // 0x03A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3AA[0x2];                                      // 0x03AA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time_1;                    // 0x03AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance_1;                // 0x03B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B4[0x4];                                      // 0x03B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_Location_1;                // 0x03B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint_1;             // 0x03D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal_1;                  // 0x03E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal_1;            // 0x0400(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat_1;                 // 0x0418(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor_1;                // 0x0420(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent_1;            // 0x0428(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName_1;             // 0x0430(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_BoneName_1;                // 0x0438(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem_1;                 // 0x0440(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex_1;            // 0x0444(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex_1;               // 0x0448(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44C[0x4];                                      // 0x044C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_TraceStart_1;              // 0x0450(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd_1;                // 0x0468(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue_1;      // 0x0480(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x0498(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_VSize_ReturnValue_1;                      // 0x04B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x04B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue_1;        // 0x04D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue_1;      // 0x04E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerCameraManager*                   CallFunc_GetOwningPlayerCameraManager_ReturnValue; // 0x0500(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_1;           // 0x0508(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_GetCameraRotation_ReturnValue;            // 0x0520(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_GreaterGreater_VectorRotator_ReturnValue; // 0x0538(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetCameraLocation_ReturnValue;            // 0x0550(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_FunctionResult_SphereDistance_ImplicitCast; // 0x0568(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSet_Result_ImplicitCast;            // 0x0570(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_574[0x4];                                      // 0x0574(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_DoubleToVector_InDouble_ImplicitCast; // 0x0578(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSet_Result_ImplicitCast_1;          // 0x0580(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_584[0x4];                                      // 0x0584(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_DoubleToVector_InDouble_ImplicitCast_1; // 0x0588(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_AimAssistReticle_C_GetCurrentSphereDistance) == 0x000008, "Wrong alignment on W_AimAssistReticle_C_GetCurrentSphereDistance");
static_assert(sizeof(W_AimAssistReticle_C_GetCurrentSphereDistance) == 0x000590, "Wrong size on W_AimAssistReticle_C_GetCurrentSphereDistance");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, SphereDistance) == 0x000000, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::SphereDistance' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, Start) == 0x000008, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::Start' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, End) == 0x000020, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::End' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CameraForward) == 0x000038, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CameraForward' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CameraLocation) == 0x000050, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CameraLocation' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, Result) == 0x000068, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::Result' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_GetOwner_ReturnValue) == 0x000070, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, K2Node_MakeArray_Array) == 0x000078, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_SphereTraceSingleByProfile_OutHit) == 0x000088, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_SphereTraceSingleByProfile_OutHit' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_SphereTraceSingleByProfile_ReturnValue) == 0x000180, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_SphereTraceSingleByProfile_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, K2Node_SwitchEnum_CmpSuccess) == 0x000181, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_bBlockingHit) == 0x000182, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_bInitialOverlap) == 0x000183, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_Time) == 0x000184, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_Distance) == 0x000188, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_Location) == 0x000190, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_ImpactPoint) == 0x0001A8, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_Normal) == 0x0001C0, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_ImpactNormal) == 0x0001D8, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_PhysMat) == 0x0001F0, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_HitActor) == 0x0001F8, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_HitComponent) == 0x000200, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_HitBoneName) == 0x000208, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_BoneName) == 0x000210, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_BoneName' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_HitItem) == 0x000218, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_ElementIndex) == 0x00021C, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_FaceIndex) == 0x000220, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_TraceStart) == 0x000228, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_TraceEnd) == 0x000240, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000258, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_GetOwner_ReturnValue_1) == 0x000270, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_GetOwner_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_VSize_ReturnValue) == 0x000278, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, K2Node_MakeArray_Array_1) == 0x000280, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_SphereTraceSingle_OutHit) == 0x000290, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_SphereTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_SphereTraceSingle_ReturnValue) == 0x000388, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_SphereTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_Conv_DoubleToVector_ReturnValue) == 0x000390, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_Conv_DoubleToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_bBlockingHit_1) == 0x0003A8, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_bBlockingHit_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_bInitialOverlap_1) == 0x0003A9, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_bInitialOverlap_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_Time_1) == 0x0003AC, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_Time_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_Distance_1) == 0x0003B0, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_Distance_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_Location_1) == 0x0003B8, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_Location_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_ImpactPoint_1) == 0x0003D0, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_ImpactPoint_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_Normal_1) == 0x0003E8, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_Normal_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_ImpactNormal_1) == 0x000400, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_ImpactNormal_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_PhysMat_1) == 0x000418, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_PhysMat_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_HitActor_1) == 0x000420, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_HitActor_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_HitComponent_1) == 0x000428, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_HitComponent_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_HitBoneName_1) == 0x000430, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_HitBoneName_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_BoneName_1) == 0x000438, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_BoneName_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_HitItem_1) == 0x000440, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_HitItem_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_ElementIndex_1) == 0x000444, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_ElementIndex_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_FaceIndex_1) == 0x000448, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_FaceIndex_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_TraceStart_1) == 0x000450, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_TraceStart_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_BreakHitResult_TraceEnd_1) == 0x000468, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_BreakHitResult_TraceEnd_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_Subtract_VectorVector_ReturnValue_1) == 0x000480, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_Subtract_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_Multiply_VectorVector_ReturnValue) == 0x000498, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_VSize_ReturnValue_1) == 0x0004B0, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_VSize_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_Add_VectorVector_ReturnValue) == 0x0004B8, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_Conv_DoubleToVector_ReturnValue_1) == 0x0004D0, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_Conv_DoubleToVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_Multiply_VectorVector_ReturnValue_1) == 0x0004E8, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_Multiply_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_GetOwningPlayerCameraManager_ReturnValue) == 0x000500, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_GetOwningPlayerCameraManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_Add_VectorVector_ReturnValue_1) == 0x000508, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_Add_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_GetCameraRotation_ReturnValue) == 0x000520, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_GetCameraRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_GreaterGreater_VectorRotator_ReturnValue) == 0x000538, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_GreaterGreater_VectorRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_GetCameraLocation_ReturnValue) == 0x000550, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_GetCameraLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, K2Node_FunctionResult_SphereDistance_ImplicitCast) == 0x000568, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::K2Node_FunctionResult_SphereDistance_ImplicitCast' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, K2Node_VariableSet_Result_ImplicitCast) == 0x000570, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::K2Node_VariableSet_Result_ImplicitCast' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_Conv_DoubleToVector_InDouble_ImplicitCast) == 0x000578, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_Conv_DoubleToVector_InDouble_ImplicitCast' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, K2Node_VariableSet_Result_ImplicitCast_1) == 0x000580, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::K2Node_VariableSet_Result_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetCurrentSphereDistance, CallFunc_Conv_DoubleToVector_InDouble_ImplicitCast_1) == 0x000588, "Member 'W_AimAssistReticle_C_GetCurrentSphereDistance::CallFunc_Conv_DoubleToVector_InDouble_ImplicitCast_1' has a wrong offset!");

// Function W_AimAssistReticle.W_AimAssistReticle_C.Tick
// 0x003C (0x003C - 0x0000)
struct W_AimAssistReticle_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_AimAssistReticle_C_Tick) == 0x000004, "Wrong alignment on W_AimAssistReticle_C_Tick");
static_assert(sizeof(W_AimAssistReticle_C_Tick) == 0x00003C, "Wrong size on W_AimAssistReticle_C_Tick");
static_assert(offsetof(W_AimAssistReticle_C_Tick, MyGeometry) == 0x000000, "Member 'W_AimAssistReticle_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_Tick, InDeltaTime) == 0x000038, "Member 'W_AimAssistReticle_C_Tick::InDeltaTime' has a wrong offset!");

// Function W_AimAssistReticle.W_AimAssistReticle_C.GetAdjustedThickness
// 0x0020 (0x0020 - 0x0000)
struct W_AimAssistReticle_C_GetAdjustedThickness final
{
public:
	double                                        NewWidth;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        NewThickness;                                      // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SafeDivide_ReturnValue;                   // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_AimAssistReticle_C_GetAdjustedThickness) == 0x000008, "Wrong alignment on W_AimAssistReticle_C_GetAdjustedThickness");
static_assert(sizeof(W_AimAssistReticle_C_GetAdjustedThickness) == 0x000020, "Wrong size on W_AimAssistReticle_C_GetAdjustedThickness");
static_assert(offsetof(W_AimAssistReticle_C_GetAdjustedThickness, NewWidth) == 0x000000, "Member 'W_AimAssistReticle_C_GetAdjustedThickness::NewWidth' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetAdjustedThickness, NewThickness) == 0x000008, "Member 'W_AimAssistReticle_C_GetAdjustedThickness::NewThickness' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetAdjustedThickness, CallFunc_SafeDivide_ReturnValue) == 0x000010, "Member 'W_AimAssistReticle_C_GetAdjustedThickness::CallFunc_SafeDivide_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_AimAssistReticle_C_GetAdjustedThickness, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000018, "Member 'W_AimAssistReticle_C_GetAdjustedThickness::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");

}

