#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_LyraArrowButton

#include "Basic.hpp"

#include "W_LyraMenuButton_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_LyraArrowButton.W_LyraArrowButton_C
// 0x0000 (0x1870 - 0x1870)
class UW_LyraArrowButton_C final : public UW_LyraMenuButton_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_LyraArrowButton_C">();
	}
	static class UW_LyraArrowButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_LyraArrowButton_C>();
	}
};
static_assert(alignof(UW_LyraArrowButton_C) == 0x000010, "Wrong alignment on UW_LyraArrowButton_C");
static_assert(sizeof(UW_LyraArrowButton_C) == 0x001870, "Wrong size on UW_LyraArrowButton_C");

}

