#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WI_ImportantNotifications

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "S_ImportantNotificationReceivedMessage_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function WI_ImportantNotifications.WI_ImportantNotifications_C.AddEntry
// 0x0080 (0x0080 - 0x0000)
struct WI_ImportantNotifications_C_AddEntry final
{
public:
	class FText                                   NotificationText;                                  // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	TSoftObjectPtr<class UTexture2D>              IconTexture;                                       // 0x0010(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, UObjectWrapper, HasGetValueTypeHash)
	TSoftObjectPtr<class UMaterialInterface>      IconMaterial;                                      // 0x0038(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, UObjectWrapper, HasGetValueTypeHash)
	const class UWI_ImportantNotificationEntry_C* OutWidget;                                         // 0x0060(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWI_ImportantNotificationEntry_C*       CallFunc_Create_ReturnValue;                       // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UOverlaySlot*                           CallFunc_AddChildToOverlay_ReturnValue;            // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_ImportantNotifications_C_AddEntry) == 0x000008, "Wrong alignment on WI_ImportantNotifications_C_AddEntry");
static_assert(sizeof(WI_ImportantNotifications_C_AddEntry) == 0x000080, "Wrong size on WI_ImportantNotifications_C_AddEntry");
static_assert(offsetof(WI_ImportantNotifications_C_AddEntry, NotificationText) == 0x000000, "Member 'WI_ImportantNotifications_C_AddEntry::NotificationText' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_AddEntry, IconTexture) == 0x000010, "Member 'WI_ImportantNotifications_C_AddEntry::IconTexture' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_AddEntry, IconMaterial) == 0x000038, "Member 'WI_ImportantNotifications_C_AddEntry::IconMaterial' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_AddEntry, OutWidget) == 0x000060, "Member 'WI_ImportantNotifications_C_AddEntry::OutWidget' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_AddEntry, CallFunc_Create_ReturnValue) == 0x000068, "Member 'WI_ImportantNotifications_C_AddEntry::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_AddEntry, CallFunc_Array_AddUnique_ReturnValue) == 0x000070, "Member 'WI_ImportantNotifications_C_AddEntry::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_AddEntry, CallFunc_AddChildToOverlay_ReturnValue) == 0x000078, "Member 'WI_ImportantNotifications_C_AddEntry::CallFunc_AddChildToOverlay_ReturnValue' has a wrong offset!");

// Function WI_ImportantNotifications.WI_ImportantNotifications_C.AnimateOutAndRemoveFromParent
// 0x0008 (0x0008 - 0x0000)
struct WI_ImportantNotifications_C_AnimateOutAndRemoveFromParent final
{
public:
	class UWI_ImportantNotificationEntry_C*       Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_ImportantNotifications_C_AnimateOutAndRemoveFromParent) == 0x000008, "Wrong alignment on WI_ImportantNotifications_C_AnimateOutAndRemoveFromParent");
static_assert(sizeof(WI_ImportantNotifications_C_AnimateOutAndRemoveFromParent) == 0x000008, "Wrong size on WI_ImportantNotifications_C_AnimateOutAndRemoveFromParent");
static_assert(offsetof(WI_ImportantNotifications_C_AnimateOutAndRemoveFromParent, Widget) == 0x000000, "Member 'WI_ImportantNotifications_C_AnimateOutAndRemoveFromParent::Widget' has a wrong offset!");

// Function WI_ImportantNotifications.WI_ImportantNotifications_C.ExecuteUbergraph_WI_ImportantNotifications
// 0x0358 (0x0358 - 0x0000)
struct WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FS_ImportantNotificationReceivedMessage Temp_struct_Variable;                              // 0x0008(0x0090)(HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0098(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UGameplayMessageSubsystem*              CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                K2Node_CustomEvent_Loaded;                         // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable;                              // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USoundCue*                              K2Node_DynamicCast_AsSound_Cue;                    // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C9[0x3];                                       // 0x00C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWI_ImportantNotificationEntry_C*       CallFunc_AddEntry_OutWidget;                       // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x00E0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x00F0(0x0008)(NoDestructor, HasGetValueTypeHash)
	class UWI_ImportantNotificationEntry_C*       K2Node_CustomEvent_Widget;                         // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAsyncAction_ListenForGameplayMessage*  CallFunc_ListenForGameplayMessages_ReturnValue;    // 0x0100(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_CreatePlayAnimationProxyObject_Result;    // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimationPlayCallbackProxy*      CallFunc_CreatePlayAnimationProxyObject_ReturnValue; // 0x0118(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAsyncAction_ListenForGameplayMessage*  Temp_object_Variable_1;                            // 0x0120(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetPayload_ReturnValue;                   // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0129(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12A[0x2];                                      // 0x012A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWI_ImportantNotificationEntry_C*       CallFunc_Array_Get_Item;                           // 0x0130(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x013C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_CustomEvent_NotificationText;               // 0x0140(0x0010)()
	TSoftObjectPtr<class UTexture2D>              K2Node_CustomEvent_IconTexture;                    // 0x0150(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	TSoftObjectPtr<class UMaterialInterface>      K2Node_CustomEvent_IconMaterial;                   // 0x0178(0x0028)(HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_Lifetime;                       // 0x01A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A4[0x4];                                      // 0x01A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class USoundCue>               K2Node_CustomEvent_SoundCue;                       // 0x01A8(0x0028)(HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D1[0x7];                                      // 0x01D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWI_ImportantNotificationEntry_C*       CallFunc_AddEntry_OutWidget_1;                     // 0x01D8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E1[0x3];                                      // 0x01E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           Temp_struct_Variable_1;                            // 0x01E4(0x0008)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1EC[0x4];                                      // 0x01EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FS_ImportantNotificationReceivedMessage Temp_struct_Variable_2;                            // 0x01F0(0x0090)(HasGetValueTypeHash)
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate_2;            // 0x0280(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_291[0x7];                                      // 0x0291(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAsyncAction_ListenForGameplayMessage*  K2Node_CustomEvent_ProxyObject;                    // 0x0298(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           K2Node_CustomEvent_ActualChannel;                  // 0x02A0(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x02A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue_1;           // 0x02A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2AA[0x2];                                      // 0x02AA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x02AC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BC[0x4];                                      // 0x02BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FS_ImportantNotificationReceivedMessage K2Node_MakeStruct_S_ImportantNotificationReceivedMessage; // 0x02C0(0x0090)(HasGetValueTypeHash)
	float                                         CallFunc_ShowNotificationWithLifetime_Lifetime_ImplicitCast; // 0x0350(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications) == 0x000008, "Wrong alignment on WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications");
static_assert(sizeof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications) == 0x000358, "Wrong size on WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, EntryPoint) == 0x000000, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::EntryPoint' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, Temp_struct_Variable) == 0x000008, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CreateDelegate_OutputDelegate) == 0x000098, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x0000A8, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CustomEvent_Loaded) == 0x0000B0, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, Temp_object_Variable) == 0x0000B8, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_DynamicCast_AsSound_Cue) == 0x0000C0, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_DynamicCast_AsSound_Cue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_DynamicCast_bSuccess) == 0x0000C8, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, Temp_int_Array_Index_Variable) == 0x0000CC, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_Event_IsDesignTime) == 0x0000D0, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_AddEntry_OutWidget) == 0x0000D8, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_AddEntry_OutWidget' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000E0, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x0000F0, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CustomEvent_Widget) == 0x0000F8, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CustomEvent_Widget' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_ListenForGameplayMessages_ReturnValue) == 0x000100, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_ListenForGameplayMessages_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_IsValid_ReturnValue) == 0x000108, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_CreatePlayAnimationProxyObject_Result) == 0x000110, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_CreatePlayAnimationProxyObject_Result' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_CreatePlayAnimationProxyObject_ReturnValue) == 0x000118, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_CreatePlayAnimationProxyObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, Temp_object_Variable_1) == 0x000120, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_GetPayload_ReturnValue) == 0x000128, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_GetPayload_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_IsValid_ReturnValue_1) == 0x000129, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, Temp_int_Loop_Counter_Variable) == 0x00012C, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_Array_Get_Item) == 0x000130, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_Add_IntInt_ReturnValue) == 0x000138, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_Array_Length_ReturnValue) == 0x00013C, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CustomEvent_NotificationText) == 0x000140, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CustomEvent_NotificationText' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CustomEvent_IconTexture) == 0x000150, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CustomEvent_IconTexture' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CustomEvent_IconMaterial) == 0x000178, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CustomEvent_IconMaterial' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CustomEvent_Lifetime) == 0x0001A0, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CustomEvent_Lifetime' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CustomEvent_SoundCue) == 0x0001A8, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CustomEvent_SoundCue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_Less_IntInt_ReturnValue) == 0x0001D0, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_AddEntry_OutWidget_1) == 0x0001D8, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_AddEntry_OutWidget_1' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_IsValid_ReturnValue_2) == 0x0001E0, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, Temp_struct_Variable_1) == 0x0001E4, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, Temp_struct_Variable_2) == 0x0001F0, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::Temp_struct_Variable_2' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CreateDelegate_OutputDelegate_2) == 0x000280, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_Array_Contains_ReturnValue) == 0x000290, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CustomEvent_ProxyObject) == 0x000298, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CustomEvent_ProxyObject' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CustomEvent_ActualChannel) == 0x0002A0, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CustomEvent_ActualChannel' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_Array_RemoveItem_ReturnValue) == 0x0002A8, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_Array_RemoveItem_ReturnValue_1) == 0x0002A9, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_Array_RemoveItem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_CreateDelegate_OutputDelegate_3) == 0x0002AC, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, K2Node_MakeStruct_S_ImportantNotificationReceivedMessage) == 0x0002C0, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::K2Node_MakeStruct_S_ImportantNotificationReceivedMessage' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications, CallFunc_ShowNotificationWithLifetime_Lifetime_ImplicitCast) == 0x000350, "Member 'WI_ImportantNotifications_C_ExecuteUbergraph_WI_ImportantNotifications::CallFunc_ShowNotificationWithLifetime_Lifetime_ImplicitCast' has a wrong offset!");

// Function WI_ImportantNotifications.WI_ImportantNotifications_C.OnLoaded_165A2A9049831B605CA3559AEB1D6542
// 0x0008 (0x0008 - 0x0000)
struct WI_ImportantNotifications_C_OnLoaded_165A2A9049831B605CA3559AEB1D6542 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_ImportantNotifications_C_OnLoaded_165A2A9049831B605CA3559AEB1D6542) == 0x000008, "Wrong alignment on WI_ImportantNotifications_C_OnLoaded_165A2A9049831B605CA3559AEB1D6542");
static_assert(sizeof(WI_ImportantNotifications_C_OnLoaded_165A2A9049831B605CA3559AEB1D6542) == 0x000008, "Wrong size on WI_ImportantNotifications_C_OnLoaded_165A2A9049831B605CA3559AEB1D6542");
static_assert(offsetof(WI_ImportantNotifications_C_OnLoaded_165A2A9049831B605CA3559AEB1D6542, Loaded) == 0x000000, "Member 'WI_ImportantNotifications_C_OnLoaded_165A2A9049831B605CA3559AEB1D6542::Loaded' has a wrong offset!");

// Function WI_ImportantNotifications.WI_ImportantNotifications_C.OnMessageReceived_591179BB46050084BC8A81A002A5FC10
// 0x0010 (0x0010 - 0x0000)
struct WI_ImportantNotifications_C_OnMessageReceived_591179BB46050084BC8A81A002A5FC10 final
{
public:
	class UAsyncAction_ListenForGameplayMessage*  ProxyObject;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           ActualChannel;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_ImportantNotifications_C_OnMessageReceived_591179BB46050084BC8A81A002A5FC10) == 0x000008, "Wrong alignment on WI_ImportantNotifications_C_OnMessageReceived_591179BB46050084BC8A81A002A5FC10");
static_assert(sizeof(WI_ImportantNotifications_C_OnMessageReceived_591179BB46050084BC8A81A002A5FC10) == 0x000010, "Wrong size on WI_ImportantNotifications_C_OnMessageReceived_591179BB46050084BC8A81A002A5FC10");
static_assert(offsetof(WI_ImportantNotifications_C_OnMessageReceived_591179BB46050084BC8A81A002A5FC10, ProxyObject) == 0x000000, "Member 'WI_ImportantNotifications_C_OnMessageReceived_591179BB46050084BC8A81A002A5FC10::ProxyObject' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_OnMessageReceived_591179BB46050084BC8A81A002A5FC10, ActualChannel) == 0x000008, "Member 'WI_ImportantNotifications_C_OnMessageReceived_591179BB46050084BC8A81A002A5FC10::ActualChannel' has a wrong offset!");

// Function WI_ImportantNotifications.WI_ImportantNotifications_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WI_ImportantNotifications_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_ImportantNotifications_C_PreConstruct) == 0x000001, "Wrong alignment on WI_ImportantNotifications_C_PreConstruct");
static_assert(sizeof(WI_ImportantNotifications_C_PreConstruct) == 0x000001, "Wrong size on WI_ImportantNotifications_C_PreConstruct");
static_assert(offsetof(WI_ImportantNotifications_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WI_ImportantNotifications_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WI_ImportantNotifications.WI_ImportantNotifications_C.Remove All Entries
// 0x0020 (0x0020 - 0x0000)
struct WI_ImportantNotifications_C_Remove_All_Entries final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_ImportantNotifications_C_Remove_All_Entries) == 0x000008, "Wrong alignment on WI_ImportantNotifications_C_Remove_All_Entries");
static_assert(sizeof(WI_ImportantNotifications_C_Remove_All_Entries) == 0x000020, "Wrong size on WI_ImportantNotifications_C_Remove_All_Entries");
static_assert(offsetof(WI_ImportantNotifications_C_Remove_All_Entries, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WI_ImportantNotifications_C_Remove_All_Entries::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_Remove_All_Entries, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WI_ImportantNotifications_C_Remove_All_Entries::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_Remove_All_Entries, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'WI_ImportantNotifications_C_Remove_All_Entries::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_Remove_All_Entries, CallFunc_Array_Get_Item) == 0x000010, "Member 'WI_ImportantNotifications_C_Remove_All_Entries::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_Remove_All_Entries, CallFunc_Array_Length_ReturnValue) == 0x000018, "Member 'WI_ImportantNotifications_C_Remove_All_Entries::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_Remove_All_Entries, CallFunc_Less_IntInt_ReturnValue) == 0x00001C, "Member 'WI_ImportantNotifications_C_Remove_All_Entries::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function WI_ImportantNotifications.WI_ImportantNotifications_C.ShowNotificationWithLifetime
// 0x0090 (0x0090 - 0x0000)
struct WI_ImportantNotifications_C_ShowNotificationWithLifetime final
{
public:
	class FText                                   NotificationText;                                  // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	TSoftObjectPtr<class UTexture2D>              IconTexture;                                       // 0x0010(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, UObjectWrapper, HasGetValueTypeHash)
	TSoftObjectPtr<class UMaterialInterface>      IconMaterial;                                      // 0x0038(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	float                                         Lifetime;                                          // 0x0060(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class USoundCue>               SoundCue;                                          // 0x0068(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(WI_ImportantNotifications_C_ShowNotificationWithLifetime) == 0x000008, "Wrong alignment on WI_ImportantNotifications_C_ShowNotificationWithLifetime");
static_assert(sizeof(WI_ImportantNotifications_C_ShowNotificationWithLifetime) == 0x000090, "Wrong size on WI_ImportantNotifications_C_ShowNotificationWithLifetime");
static_assert(offsetof(WI_ImportantNotifications_C_ShowNotificationWithLifetime, NotificationText) == 0x000000, "Member 'WI_ImportantNotifications_C_ShowNotificationWithLifetime::NotificationText' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ShowNotificationWithLifetime, IconTexture) == 0x000010, "Member 'WI_ImportantNotifications_C_ShowNotificationWithLifetime::IconTexture' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ShowNotificationWithLifetime, IconMaterial) == 0x000038, "Member 'WI_ImportantNotifications_C_ShowNotificationWithLifetime::IconMaterial' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ShowNotificationWithLifetime, Lifetime) == 0x000060, "Member 'WI_ImportantNotifications_C_ShowNotificationWithLifetime::Lifetime' has a wrong offset!");
static_assert(offsetof(WI_ImportantNotifications_C_ShowNotificationWithLifetime, SoundCue) == 0x000068, "Member 'WI_ImportantNotifications_C_ShowNotificationWithLifetime::SoundCue' has a wrong offset!");

}

