#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WI_SocialRecentPlayerEntry

#include "Basic.hpp"

#include "WI_SocialRecentPlayerEntry_classes.hpp"
#include "WI_SocialRecentPlayerEntry_parameters.hpp"


namespace SDK
{

// Function WI_SocialRecentPlayerEntry.WI_SocialRecentPlayerEntry_C.ExecuteUbergraph_WI_SocialRecentPlayerEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWI_SocialRecentPlayerEntry_C::ExecuteUbergraph_WI_SocialRecentPlayerEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WI_SocialRecentPlayerEntry_C", "ExecuteUbergraph_WI_SocialRecentPlayerEntry");

	Params::WI_SocialRecentPlayerEntry_C_ExecuteUbergraph_WI_SocialRecentPlayerEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WI_SocialRecentPlayerEntry.WI_SocialRecentPlayerEntry_C.GetFormattedLastSeenTimeSpan
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FTimespan                        LastSeenTimespan                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWI_SocialRecentPlayerEntry_C::GetFormattedLastSeenTimeSpan(const struct FTimespan& LastSeenTimespan)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WI_SocialRecentPlayerEntry_C", "GetFormattedLastSeenTimeSpan");

	Params::WI_SocialRecentPlayerEntry_C_GetFormattedLastSeenTimeSpan Parms{};

	Parms.LastSeenTimespan = std::move(LastSeenTimespan);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WI_SocialRecentPlayerEntry.WI_SocialRecentPlayerEntry_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWI_SocialRecentPlayerEntry_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WI_SocialRecentPlayerEntry_C", "PreConstruct");

	Params::WI_SocialRecentPlayerEntry_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

