#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WI_SocialBlockedPlayerEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "JP_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WI_SocialBlockedPlayerEntry.WI_SocialBlockedPlayerEntry_C
// 0x0008 (0x0320 - 0x0318)
class UWI_SocialBlockedPlayerEntry_C final : public USocialBlockedPlayerEntryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0318(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WI_SocialBlockedPlayerEntry(int32 EntryPoint);
	void GetLocalizedStatusInfo(class FText* StatusText, struct FLinearColor* Color);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WI_SocialBlockedPlayerEntry_C">();
	}
	static class UWI_SocialBlockedPlayerEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWI_SocialBlockedPlayerEntry_C>();
	}
};
static_assert(alignof(UWI_SocialBlockedPlayerEntry_C) == 0x000008, "Wrong alignment on UWI_SocialBlockedPlayerEntry_C");
static_assert(sizeof(UWI_SocialBlockedPlayerEntry_C) == 0x000320, "Wrong size on UWI_SocialBlockedPlayerEntry_C");
static_assert(offsetof(UWI_SocialBlockedPlayerEntry_C, UberGraphFrame) == 0x000318, "Member 'UWI_SocialBlockedPlayerEntry_C::UberGraphFrame' has a wrong offset!");

}

