#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WI_SeasonPassReward_CatalogItem_Default

#include "Basic.hpp"


namespace SDK::Params
{

// Function WI_SeasonPassReward_CatalogItem_Default.WI_SeasonPassReward_CatalogItem_Default_C.ExecuteUbergraph_WI_SeasonPassReward_CatalogItem_Default
// 0x0004 (0x0004 - 0x0000)
struct WI_SeasonPassReward_CatalogItem_Default_C_ExecuteUbergraph_WI_SeasonPassReward_CatalogItem_Default final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WI_SeasonPassReward_CatalogItem_Default_C_ExecuteUbergraph_WI_SeasonPassReward_CatalogItem_Default) == 0x000004, "Wrong alignment on WI_SeasonPassReward_CatalogItem_Default_C_ExecuteUbergraph_WI_SeasonPassReward_CatalogItem_Default");
static_assert(sizeof(WI_SeasonPassReward_CatalogItem_Default_C_ExecuteUbergraph_WI_SeasonPassReward_CatalogItem_Default) == 0x000004, "Wrong size on WI_SeasonPassReward_CatalogItem_Default_C_ExecuteUbergraph_WI_SeasonPassReward_CatalogItem_Default");
static_assert(offsetof(WI_SeasonPassReward_CatalogItem_Default_C_ExecuteUbergraph_WI_SeasonPassReward_CatalogItem_Default, EntryPoint) == 0x000000, "Member 'WI_SeasonPassReward_CatalogItem_Default_C_ExecuteUbergraph_WI_SeasonPassReward_CatalogItem_Default::EntryPoint' has a wrong offset!");

}

